// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbpKgPucdgQY7gT0lJgDE2R6YjmPwBCw',
    appId: '1:738725368252:web:facb2dea32763567c65bb9',
    messagingSenderId: '738725368252',
    projectId: 'sos-app-b09b1',
    authDomain: 'sos-app-b09b1.firebaseapp.com',
    databaseURL: 'https://sos-app-b09b1-default-rtdb.firebaseio.com',
    storageBucket: 'sos-app-b09b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtFYZ9Pm7fZY2eyYCiehugyy5tklvL828',
    appId: '1:738725368252:android:565749834e556983c65bb9',
    messagingSenderId: '738725368252',
    projectId: 'sos-app-b09b1',
    databaseURL: 'https://sos-app-b09b1-default-rtdb.firebaseio.com',
    storageBucket: 'sos-app-b09b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5yPC0zRk8CN1nCgASVfhC-O7UUIxw9gk',
    appId: '1:738725368252:ios:1e01195b11080093c65bb9',
    messagingSenderId: '738725368252',
    projectId: 'sos-app-b09b1',
    databaseURL: 'https://sos-app-b09b1-default-rtdb.firebaseio.com',
    storageBucket: 'sos-app-b09b1.appspot.com',
    iosBundleId: 'com.example.flutterTrainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5yPC0zRk8CN1nCgASVfhC-O7UUIxw9gk',
    appId: '1:738725368252:ios:1e01195b11080093c65bb9',
    messagingSenderId: '738725368252',
    projectId: 'sos-app-b09b1',
    databaseURL: 'https://sos-app-b09b1-default-rtdb.firebaseio.com',
    storageBucket: 'sos-app-b09b1.appspot.com',
    iosBundleId: 'com.example.flutterTrainingApp',
  );
}
